id: org.eclipse.che.samples.dummy-plugin
version: 1.0.0
type: Theia plugin
name: Dummy-plugin
title: Dummy theia plugin
description: Dummy theia plugin
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
url: https://github.com/azatsarynnyy/che7-plugin-registry/blob/master/org.eclipse.che.samples.dummy-plugin/1.0.0/sag_is_navigator.theia?raw=true
