id: redhat.vscode-openshift-connector
version: 0.0.17
type: VS Code extension
name: OpenShift Connector
title: OpenShift Connector
description: Interacting with Red Hat OpenShift clusters and providing a streamlined developer experience using Eclipse Che
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
publisher: Red Hat, Inc.
repository: https://github.com/redhat-developer/vscode-openshift-tools
category: Other
firstPublicationDate: "2019-02-28"
attributes:
  extension: "vscode:extension/redhat.vscode-openshift-connector"
  containerImage: "azatsarynnyy/che-openshift-connector-plugin:0.0.17"
