id: ms-kubernetes-tools.vscode-kubernetes-tools
version: 0.1.16
type: VS Code extension
name: Kubernetes
title: Kubernetes Tools
description: Develop, deploy and debug Kubernetes applications
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
publisher: Red Hat, Inc.
repository: https://github.com/Azure/vscode-kubernetes-tools
category: Other
firstPublicationDate: "2019-02-21"
attributes:
  extension: "vscode:extension/ms-kubernetes-tools.vscode-kubernetes-tools"
  containerImage: "azatsarynnyy/che-kubernetes-tools-plugin:0.1.16"
