id: terminal-sample
version: 0.0.1
type: Theia plugin
name: Theia Sample Plugin - Terminal
title: Theia Sample Plugin - Terminal
description: Theia Sample Plugin - Terminal
url: https://github.com/AndrienkoAleksandr/che-theia-samples/blob/useShForRemotePlugin/samples/terminal-plugin/terminal_plugin.theia?raw=true
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
firstPublicationDate: "2019-03-15"
attributes:
  containerImage: "eclipse/che-theia-endpoint-runtime:next"
